name: main
on:
  push:
    branches:
    - master

jobs:
  job-0:
    runs-on: ubuntu-latest
    steps:
    - name: one
      run: echo "run job-0 [one]"

  job-1:
    runs-on: ubuntu-latest
    needs:
    - job-0
    steps:
    - name: two
      run: echo "run job-1 [two]"
